### ISSUE TITLE
question about the ablation study on POS

### ISSUE THREAD

**Issue by speedcell4** [minghao-wu/CRF-AE#2]
Hi~ 

I got two questions about the POS feature.

1. have you tested using only the POS as additional feature? (since table (3) shows the performance after removing POS, not adding). if yes, could you please share the number?
2. what do you mean by "Both features are based on the implementation of spaCy" in section (2.2), you re-annotated the POS by using spaCy? instead of just using the POS annotations from CoNLL2003?

**Comment by minghao-wu** [comment]
1. Short answer, No. I think removing feature types one by one is a better approach to demonstrate the effectiveness of each feature type, since feature types share parameters and interact with each other.

2. Good question. One of my reviewer asked similar question. POS tags used in this work are generated by spaCy, which is a more realistic setting, instead of golden ones. I did not run experiment with golden POS tags when inferencing. Not sure if the performance will improve further.

**Comment by speedcell4** [comment]
Thank you so much, these answers really help~

**Comment by speedcell4** [comment]
actually, I tried to reproduce your results, but I only used the golden POS tags without the other features you mentioned in your paper. but this modification hurt the performance
